loglevel=INFO
sf.apiversion=62.0
includechangedata=true
metadataitems=Flow,CustomObject,CustomField
metadataitemstoskip=
includenamespaceditems=false
#skipmanagedstateinstalled=true
includenulldate=true

#ApexClass
ApexClass.skipmanagedstateinstalled=true

#ApexComponent
ApexComponent.skipmanagedstateinstalled=true

#ApexPage
ApexPage.skipmanagedstateinstalled=true

#ApexTrigger
ApexTrigger.skipmanagedstateinstalled=true

#CustomField.skipmanagedstateinstalled=true
CustomField.forceincludefieldtypes=Picklist,Picklist (Multi-Select)
CustomField.forceincludenamespaces=SBQQ,agf

#CustomObjectTranslation
CustomObjectTranslation.includepatterns=.*-en_US


#Flow
#Flow.limittoactive=false 
Flow.includeallversions=true